var obj = {
    "id": "",
    "ordercode": "PO20210220102307306048",
    "ordertitle": "测试",
    "purcompanyid": "1265154656556871681",
    "purcompanyname": "巴拉童装",
    "supplierid": "1265195468443381761",
    "suppliername": "GS国际有限公司",
    "businessdate": "2021-02-20 10:23:07",
    "currencyid": "1176016857577676802",
    "currencyname": "CNY",
    "sourcebillid": "",
    "sourcetype": "NONE",
    "sourcebilldesc": "",
    "billstate": "",
    "mattotalvalue": 0,
    "totalvalue": 0,
    "feeaddvalue": 0,
    "feecutvalue": 0,
    "payflag": "",
    "invoiceflag": "",
    "receiveflag": "",
    "blankoutflag": false,
    "isneedappointment": false,
    "appointmentflag": "",
    "sendflag": "",
    "orderFilesList": [],
    "orderLinkManList": [
        {
            "companyid": "1265154656556871681",
            "companyname": "巴拉童装",
            "id": "",
            "linkmail": "122345@qq.com",
            "linkmanid": "1265154140204552194",
            "linkmanname": "陈萌萌",
            "linktel": "13698601500",
            "linktype": "purchase",
            "orderid": ""
        },
        {
            "companyid": "",
            "companyname": "",
            "id": "",
            "linkmail": "",
            "linkmanid": "",
            "linkmanname": "",
            "linktel": "",
            "linktype": "supplier",
            "orderid": ""
        }
    ],
    "orderItemList": [
        {
            "id": "",
            "orderid": "",
            "materialid": "",
            "materialname": "001",
            "materialdescription": "",
            "purquantity": 1,
            "purunitid": "0001",
            "purunitname": "个",
            "purprice": 10,
            "purvalue": 0,
            "feeaddvalue": 0,
            "feecutvalue": 0,
            "matvalue": 0,
            "currencyid": "",
            "currencyname": "",
            "deliveryaddr": "中国/山东省/济南市浪潮路1036号",
            "deliverydate": "2021-02-20 00:00:00",
            "deliveryrequirement": "",
            "receivequantity": 0,
            "receiveflag": "",
            "invoicequantity": 0,
            "invoiceflag": "",
            "itemstate": "",
            "sourcetype": "RFQ",
            "sourcebillid": "",
            "sourcebillitemid": "",
            "orderFeeList": []
        }
    ],
    "orderFeeList": [],
    "orderPayPlanList": [
        {
            "id": "",
            "orderid": "",
            "paydate": "",
            "payflag": "NONE",
            "payplancode": "",
            "payplandate": "2021-02-27",
            "payplanname": "账期1",
            "payplanrequirment": "",
            "payplanvalue": 0,
            "payrate": 100,
            "payvalue": 0
        }
    ]
}